# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: InitWorker.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'InitWorker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10InitWorker.proto\"\x94\x02\n\x0fInitWorkerProto\x12\x12\n\x05JobID\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x10\n\x03Url\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x17\n\nReportName\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x13\n\x0bInputTraits\x18\x04 \x03(\t\x12\x1b\n\x13SystemPropertyNames\x18\x05 \x03(\t\x12\x0f\n\x07Outputs\x18\x06 \x03(\t\x12\x18\n\x0bResetRunner\x18\x07 \x01(\x08H\x03\x88\x01\x01\x12\x1e\n\x11PreRunSimulations\x18\x08 \x01(\x08H\x04\x88\x01\x01\x42\x08\n\x06_JobIDB\x06\n\x04_UrlB\r\n\x0b_ReportNameB\x0e\n\x0c_ResetRunnerB\x14\n\x12_PreRunSimulationsB\x14\xaa\x02\x11protobuf.messagesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'InitWorker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\021protobuf.messages'
  _globals['_INITWORKERPROTO']._serialized_start=21
  _globals['_INITWORKERPROTO']._serialized_end=297
# @@protoc_insertion_point(module_scope)
