# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: InitWorkersResponse.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'InitWorkersResponse.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19InitWorkersResponse.proto\"\xa4\x01\n\x18InitWorkersResponseProto\x12\x19\n\x0cTotalWorkers\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x1b\n\x0eWorkersStarted\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x1a\n\rWorkersFailed\x18\x03 \x01(\x05H\x02\x88\x01\x01\x42\x0f\n\r_TotalWorkersB\x11\n\x0f_WorkersStartedB\x10\n\x0e_WorkersFailedB\x14\xaa\x02\x11protobuf.messagesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'InitWorkersResponse_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\021protobuf.messages'
  _globals['_INITWORKERSRESPONSEPROTO']._serialized_start=30
  _globals['_INITWORKERSRESPONSEPROTO']._serialized_end=194
# @@protoc_insertion_point(module_scope)
