# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: InitApsimResponse.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'InitApsimResponse.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17InitApsimResponse.proto\"\xb3\x01\n\x16InitApsimResponseProto\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\r\n\x05JobID\x18\x02 \x01(\t\x12\x19\n\x0c\x46irstRunTime\x18\x03 \x01(\x01H\x00\x88\x01\x01\x12\x1a\n\rSecondRunTime\x18\x04 \x01(\x01H\x01\x88\x01\x01\x12\x16\n\tRunSource\x18\x05 \x01(\tH\x02\x88\x01\x01\x42\x0f\n\r_FirstRunTimeB\x10\n\x0e_SecondRunTimeB\x0c\n\n_RunSourceB\x14\xaa\x02\x11protobuf.messagesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'InitApsimResponse_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\021protobuf.messages'
  _globals['_INITAPSIMRESPONSEPROTO']._serialized_start=28
  _globals['_INITAPSIMRESPONSEPROTO']._serialized_end=207
# @@protoc_insertion_point(module_scope)
