# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: InitApsim.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'InitApsim.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ApsimConfig_pb2 as ApsimConfig__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fInitApsim.proto\x1a\x11\x41psimConfig.proto\"\xf2\x01\n\x0eInitApsimProto\x12\r\n\x05JobID\x18\x01 \x01(\t\x12\n\n\x02ID\x18\x02 \x01(\x05\x12\x10\n\x03Url\x18\x03 \x01(\tH\x00\x88\x01\x01\x12(\n\rConfiguration\x18\x04 \x01(\x0b\x32\x11.ApsimConfigProto\x12\x18\n\x0bResetRunner\x18\x05 \x01(\x08H\x01\x88\x01\x01\x12\x1e\n\x11PreRunSimulations\x18\x06 \x01(\x08H\x02\x88\x01\x01\x12!\n\x19WaitForJobsTimeoutSeconds\x18\x07 \x01(\x05\x42\x06\n\x04_UrlB\x0e\n\x0c_ResetRunnerB\x14\n\x12_PreRunSimulationsB\x14\xaa\x02\x11protobuf.messagesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'InitApsim_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\021protobuf.messages'
  _globals['_INITAPSIMPROTO']._serialized_start=39
  _globals['_INITAPSIMPROTO']._serialized_end=281
# @@protoc_insertion_point(module_scope)
