# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RegisterApsimRunner.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'RegisterApsimRunner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19RegisterApsimRunner.proto\"X\n\x18RegisterApsimRunnerProto\x12\x0f\n\x02ID\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x16\n\tIPAddress\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x05\n\x03_IDB\x0c\n\n_IPAddressB\x14\xaa\x02\x11protobuf.messagesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RegisterApsimRunner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\021protobuf.messages'
  _globals['_REGISTERAPSIMRUNNERPROTO']._serialized_start=29
  _globals['_REGISTERAPSIMRUNNERPROTO']._serialized_end=117
# @@protoc_insertion_point(module_scope)
