# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RegisterService.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'RegisterService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15RegisterService.proto\"\x90\x01\n\x14RegisterServiceProto\x12\x11\n\x04Name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04Type\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x16\n\tIpAddress\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x11\n\x04Port\x18\x04 \x01(\tH\x03\x88\x01\x01\x42\x07\n\x05_NameB\x07\n\x05_TypeB\x0c\n\n_IpAddressB\x07\n\x05_PortB\x14\xaa\x02\x11protobuf.messagesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RegisterService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\021protobuf.messages'
  _globals['_REGISTERSERVICEPROTO']._serialized_start=26
  _globals['_REGISTERSERVICEPROTO']._serialized_end=170
# @@protoc_insertion_point(module_scope)
