# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RelayApsim.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'RelayApsim.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Types_pb2 as Types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10RelayApsim.proto\x1a\x0bTypes.proto\"\xd9\x01\n\x0fRelayApsimProto\x12\x12\n\x05JobID\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0bIndividuals\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12!\n\x06Inputs\x18\x03 \x03(\x0b\x32\x11.DoubleArrayProto\x12*\n\x0fSimulationNames\x18\x04 \x03(\x0b\x32\x11.StringArrayProto\x12/\n\x14SystemPropertyValues\x18\x05 \x03(\x0b\x32\x11.StringArrayProtoB\x08\n\x06_JobIDB\x0e\n\x0c_IndividualsB\x14\xaa\x02\x11protobuf.messagesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RelayApsim_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\021protobuf.messages'
  _globals['_RELAYAPSIMPROTO']._serialized_start=34
  _globals['_RELAYAPSIMPROTO']._serialized_end=251
# @@protoc_insertion_point(module_scope)
