# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RunApsimResponse.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'RunApsimResponse.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ApsimResult_pb2 as ApsimResult__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16RunApsimResponse.proto\x1a\x11\x41psimResult.proto\"\xc6\x01\n\x15RunApsimResponseProto\x12\x12\n\x05JobID\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0f\n\x02ID\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x0e\n\x06\x46ields\x18\x03 \x03(\t\x12\x1f\n\x04Rows\x18\x04 \x03(\x0b\x32\x11.ApsimResultProto\x12\x14\n\x07RunTime\x18\x05 \x01(\x01H\x02\x88\x01\x01\x12\x16\n\tRunSource\x18\x06 \x01(\tH\x03\x88\x01\x01\x42\x08\n\x06_JobIDB\x05\n\x03_IDB\n\n\x08_RunTimeB\x0c\n\n_RunSourceB\x14\xaa\x02\x11protobuf.messagesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RunApsimResponse_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\021protobuf.messages'
  _globals['_RUNAPSIMRESPONSEPROTO']._serialized_start=46
  _globals['_RUNAPSIMRESPONSEPROTO']._serialized_end=244
# @@protoc_insertion_point(module_scope)
