# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RunApsim.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'RunApsim.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eRunApsim.proto\"\xbe\x01\n\rRunApsimProto\x12\x12\n\x05JobID\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0f\n\x02ID\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x13\n\x0bInputTraits\x18\x03 \x03(\t\x12\x0e\n\x06Values\x18\x04 \x03(\x01\x12\x17\n\x0fSimulationNames\x18\x05 \x03(\t\x12\x1b\n\x13SystemPropertyNames\x18\x06 \x03(\t\x12\x1c\n\x14SystemPropertyValues\x18\x07 \x03(\tB\x08\n\x06_JobIDB\x05\n\x03_IDB\x14\xaa\x02\x11protobuf.messagesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RunApsim_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\021protobuf.messages'
  _globals['_RUNAPSIMPROTO']._serialized_start=19
  _globals['_RUNAPSIMPROTO']._serialized_end=209
# @@protoc_insertion_point(module_scope)
