version: '3'

services:
  crop-gen-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cropgen
    container_name: cropgen
    ports:
      - 27746:27746
    networks:
      - q-network

networks:
  q-network:
    name: custom_qnetwork
    external: true