version: '3'

services:
  crop-gen-app:
    build: .
    image: crop-gen
    ports:
      - 32767:32767
    networks:
      - q-network

networks:
  q-network:
    name: custom_qnetwork
    external: true