version: '3'

services:
  cropgen:
    image: ${DOCKER_REGISTRY-}cropgen
    container_name: cropgen
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5678:5678"
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 main.py "]
    networks:
      - q-network

networks:
  q-network:
    name: custom_qnetwork
    external: true