name: BuildAndArchiveSingularityImage

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (archive/copy). Archive=Store image in GitHub Action. Copy=Copy image to Server.'
        required: true
        default: 'copy'

jobs:

  build:

    strategy:
      matrix:
        python-version: ["3.10"]

    runs-on: ubuntu-latest

    env:
      APP_NAME: 'CropGen'
      SINGULARITY_DEF_NAME: 'cropgen'
      VERSION_FILE_PATH: version.txt
      GIT_DETAILS_FILE_PATH: git_details.txt
      SINGULARITY_IMAGE_FILE_PATH: ''
      SINGULARITY_IMAGE_FILE_NAME: ''
      SINGULARITY_DEFINITION_FILE_NAME: ''
      ARCHIVE_FILE_NAME: ''
      INPUT_ACTION_COPY: 'copy'
      INPUT_ACTION_ARCHIVE: 'archive'

    steps:

    # Update paths with app name
    - 
      name: Update Filenames with Version
      run: |            
          echo "SINGULARITY_DEFINITION_FILE_NAME=${{ env.SINGULARITY_DEF_NAME }}.def" >> $GITHUB_ENV


    # Add key to ssh agent
    - 
        name: Add SSH key
        if: ${{ github.event.inputs.action == env.INPUT_ACTION_COPY }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.REMOTE_SERVER_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa


    # Add server to known hosts
    - 
        name: Add remote host to known_hosts
        if: ${{ github.event.inputs.action == env.INPUT_ACTION_COPY }}
        run: |
            mkdir -p ~/.ssh
            ssh-keyscan -H "${{ secrets.REMOTE_SERVER_HOST }}" >> ~/.ssh/known_hosts
            chmod 600 ~/.ssh/known_hosts            
            cat ~/.ssh/known_hosts


    # Test SSH Connection to the built images destination. 
    - 
        name: Test SSH Connection to the server
        if: ${{ github.event.inputs.action == env.INPUT_ACTION_COPY }}
        run: |
            echo "Testing SSH connection and ensuring the directory exists on the remote server..."
            ssh -o BatchMode=yes "${{ secrets.REMOTE_SERVER_USERNAME }}@${{ secrets.REMOTE_SERVER_HOST }}" "
              if [ ! -d '${{ secrets.SERVER_BUILT_IMAGES_DEST }}' ]; then
                echo 'Directory does not exist. Creating ${{ secrets.SERVER_BUILT_IMAGES_DEST }}...';
                mkdir -p '${{ secrets.SERVER_BUILT_IMAGES_DEST }}';
                if [ \$? -eq 0 ]; then
                  echo 'Directory created successfully.';
                else
                  echo 'Failed to create directory ${{ secrets.SERVER_BUILT_IMAGES_DEST }}!' >&2;
                  exit 1;
                fi
              else
                echo 'Directory already exists: ${{ secrets.SERVER_BUILT_IMAGES_DEST }}';
              fi"


    # Checkout the source code (including the submodules)
    - 
      name: Checkout
      uses: actions/checkout@v4
      with:
          token: ${{ secrets.PAT_TOKEN }}
          submodules: 'recursive'
          fetch-depth: 0


    # Initialize Submodules (ensure they are properly loaded)
    -
      name: Initialize Submodules
      run: git submodule update --init --recursive


    # Read and update the version
    - 
        name: Update Version File
        id: version_update
        run: |
            # Read the current version from version.txt
            current_version=$(cat ${{ env.VERSION_FILE_PATH }})
            echo "Current version: $current_version"

            # Increment the patch version
            new_version=$(echo $current_version | awk -F. '{printf "%d.%d.%d", $1, $2, $3+1}')
            echo "New version: $new_version"

            # Update the version.txt file with the new version
            echo $new_version > ${{ env.VERSION_FILE_PATH }}

            # Display the updated file for debugging
            cat ${{ env.VERSION_FILE_PATH }}

            # Output the new version for later steps
            echo "new_version=$new_version" >> $GITHUB_ENV


    # Update filenames with version number
    - name: Update Filenames with Version
      run: |
          # Use temporary local variables so that we can use them below.
          # You can't use an env var that has only just been set, within the same step.
          ARCHIVE_FILE_NAME=${{ env.SINGULARITY_DEF_NAME }}_${{ env.new_version }}
          SINGULARITY_IMAGE_FILE_NAME=${{ env.SINGULARITY_DEF_NAME }}_${{ env.new_version }}.sif
          SINGULARITY_IMAGE_FILE_PATH=${SINGULARITY_IMAGE_FILE_NAME}

          # Set the env vars.
          echo "SINGULARITY_IMAGE_FILE_NAME=${SINGULARITY_IMAGE_FILE_NAME}" >> $GITHUB_ENV
          echo "SINGULARITY_IMAGE_FILE_PATH=${SINGULARITY_IMAGE_FILE_PATH}" >> $GITHUB_ENV
          echo "ARCHIVE_FILE_NAME=${ARCHIVE_FILE_NAME}" >> $GITHUB_ENV


    # Log Git details for the main repository
    - 
        name: Log Main Repository Details
        run: |
            # Ensure the directory exists before attempting to write to the file
            mkdir -p $(dirname ${{ env.GIT_DETAILS_FILE_PATH }})

            # Write the CSV header
            echo "Repository,Branch,Commit SHA,Last Commit Date,Last Commit Message,Tags,Repository URL" > "${{ env.GIT_DETAILS_FILE_PATH }}"

            # Log details for the main repository
            repo_name=$(basename "$(pwd)")
            branch=$(git rev-parse --abbrev-ref HEAD)
            commit_sha=$(git rev-parse HEAD)
            commit_date=$(git show -s --format=%ci HEAD)
            commit_message=$(git log -1 --pretty=%B | tr '\n' ' ')
            tags=${{ env.new_version }}
            repo_url=$(git remote get-url origin)

            echo "$repo_name,$branch,$commit_sha,$commit_date,\"$commit_message\",\"$tags\",\"$repo_url\"" >> "${{ env.GIT_DETAILS_FILE_PATH }}"


    # Log Git details for submodules
    - 
        name: Log Submodule Details
        run: |
            # Append details for submodules to the same file
            git submodule foreach --quiet '
            repo_path=$(dirname "$PWD")/"$sm_path"
            if [ -d "$repo_path" ]; then
                repo_name=$(basename "$repo_path")
                branch=$(git -C "$repo_path" rev-parse --abbrev-ref HEAD)
                commit_sha=$(git -C "$repo_path" rev-parse HEAD)
                commit_date=$(git -C "$repo_path" show -s --format=%ci HEAD)
                commit_message=$(git -C "$repo_path" log -1 --pretty=%B | tr "\n" " ")
                tags=$(git -C "$repo_path" describe --tags --always)
                repo_url=$(git -C "$repo_path" remote get-url origin)

                echo "$repo_name,$branch,$commit_sha,$commit_date,\"$commit_message\",\"$tags\",\"$repo_url\""
            else
                echo "Submodule path $repo_path does not exist or is not initialized" >&2
            fi' >> "${{ env.GIT_DETAILS_FILE_PATH }}"


    # Print details file for debugging or verification
    - 
        name: Print Git Details
        run: cat ${{ env.GIT_DETAILS_FILE_PATH }}


    # Setup .NET
    - 
      name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        

    # Print out the python version.
    - 
      name: Display Python version
      run: python -c "import sys; print(sys.version)"


    # Install dependencies.
    - 
      name: Install dependencies
      run: pip install -r requirements.txt


    # Install Apptainer
    - 
        name: Install Apptainer
        uses: eWaterCycle/setup-apptainer@v2
        with:
            apptainer-version: 1.1.2


    # Print Apptainer Version
    - 
        name: Print Apptainer Version
        run: |
            apptainer --version


    # Build Apptainer Image
    - 
        name: Build Apptainer Image        
        run: |
            sudo apptainer build ${{ env.SINGULARITY_IMAGE_FILE_NAME }} ${{ env.SINGULARITY_DEFINITION_FILE_NAME }}


    # Sanity check that the resulting files are there.
    - 
        name: Ensure files exist
        run: |
            if [ -f "${{ env.GIT_DETAILS_FILE_PATH }}" ]; then 
              echo "${{ env.GIT_DETAILS_FILE_PATH }} exists"; 
            else 
              echo "${{ env.GIT_DETAILS_FILE_PATH }} does not exist"; 
              exit 1; 
            fi
            if [ -f "${{ env.SINGULARITY_IMAGE_FILE_PATH }}" ]; then 
              echo "${{ env.SINGULARITY_IMAGE_FILE_PATH }} exists"; 
            else 
              echo "${{ env.SINGULARITY_IMAGE_FILE_PATH }} does not exist"; 
              exit 1; 
            fi

    
    # Optionally Copy the Files
    - 
        name: Copy Files to Server
        if: ${{ github.event.inputs.action == env.INPUT_ACTION_COPY }}
        run: |
            scp -v -o StrictHostKeyChecking=no "${{ env.SINGULARITY_IMAGE_FILE_PATH }}" "${{ secrets.REMOTE_SERVER_USERNAME }}@${{ secrets.REMOTE_SERVER_HOST }}:${{ secrets.SERVER_BUILT_IMAGES_DEST }}"


    # Archive the Zip File
    - 
        name: Archive Zip File
        if: ${{ github.event.inputs.action == env.INPUT_ACTION_ARCHIVE }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARCHIVE_FILE_NAME }}
          path: |
              ${{ env.GIT_DETAILS_FILE_PATH }}
              ${{ env.SINGULARITY_IMAGE_FILE_PATH }}
          retention-days: 1
          overwrite: true


    # Commit and Push Updated Version
    - 
        name: Commit Updated Version
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
        run: |
            # Configure Git user
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"

            # Commit the updated version.txt
            git add ${{ env.VERSION_FILE_PATH }}
            git commit -m "Increment version to ${{ env.new_version }}"

            # Create and push the tag
            git tag -a ${{ env.new_version }} -m "Release version ${{ env.new_version }}"
            git push origin ${{ env.new_version }}

            # Push the commit
            git push

