name: CropGen Workflow

# Set when this runs.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Add the job.
jobs:
  test:
    name: CropGen Workflow.
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run unit tests
      run: python run_tests.py

    # - name: Login to Docker Hub
    #   run: docker login -u <DOCKERHUB_USERNAME> -p <DOCKERHUB_PASSWORD>
    #   env:
    #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    #     DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

    # - name: Push Docker image to Docker Hub
    #   run: docker push <DOCKERHUB_USERNAME>/<REPOSITORY_NAME>:latest